### ISSUE TITLE
请教一下如何实现长按？

### ISSUE THREAD

**Issue by VA1ue-0268** [Sucareto/Mai2Touch#1]
发送一个触控数据包好像只会点一次，想请教一下大佬如何实现长按一个区域，谢谢！

**Comment by Sucareto** [comment]
不会呀，你不发新数据包就不会松开的
例如：
发送0x111，按下A1，A2，A3
不发送新数据包，保持按下A1，A2，A3
发送0x001，松开A3，A2，继续保持按下A1

**Comment by VA1ue-0268** [comment]
是我的游戏程序有问题还是代码（如图）写的有问题qwq

这样写的话应该是全部按键连续按完才结束吧？但是效果（视频）并不是这样哎，，

![image](https://user-images.githubusercontent.com/17075414/158304805-ac656197-e431-4d56-888f-dd40027fb353.png)

https://user-images.githubusercontent.com/17075414/158305676-771cf2a4-cacd-4e01-882e-a3693e8b2ee3.mp4

**Comment by Sucareto** [comment]
我这个TouchSend示例，默认是只有一个触摸点，依次跑完所有触摸区的

**Comment by VA1ue-0268** [comment]
嗯嗯，但是我把<<=改成了+= TPD<<1，按理来说应该是全部一起按下的呀？给我整迷糊了qwq

**Comment by Sucareto** [comment]
不要`+=`，用`|=`呀

**Comment by VA1ue-0268** [comment]
噢噢搞错了，但是改过来还是一样哎，，

https://user-images.githubusercontent.com/17075414/158310121-83f51e40-55ea-4c5c-aef2-cf4a3c93f9d5.mp4



这个是串口输出，看着也没毛病啊qwq
![image](https://user-images.githubusercontent.com/17075414/158310077-7fbff2e8-9db5-43ed-a47e-236eee3080a6.png)

**Comment by Sucareto** [comment]
oh还有个问题，运算符优先级的问题
`TPD = TPD | (TPD << 1);`
我晚上回去测一下~

**Comment by VA1ue-0268** [comment]
好~麻烦dalao了(=・ω・=)

**Comment by VA1ue-0268** [comment]
破案了，在mai2.ini中把DummyTouchPanel改为0就可以了，，，

**Comment by Sucareto** [comment]
草，你居然没关dummy就测试，怎么可能有用嘛

**Comment by VA1ue-0268** [comment]
dbqdbq是我大意了

**Comment by Sucareto** [comment]
手台开发加油啦~期待你的作品！

**Comment by VA1ue-0268** [comment]
谢谢大佬~但是现在有个新问题，连点同一个好像不行qwq

**Comment by Sucareto** [comment]
连点，是按下，松开，再按下

**Comment by VA1ue-0268** [comment]
嗯嗯，麻烦大佬再帮忙看看qwq
下面是串口图片和效果视频

![image](https://user-images.githubusercontent.com/17075414/158346844-ebc04c79-8c5c-4825-8700-b7de2369f5fd.png)

https://user-images.githubusercontent.com/17075414/158346822-487e099c-e4be-473b-a1a4-b8eb61486c5f.mp4

**Comment by Sucareto** [comment]
我的开发板坏掉了，我得晚点才能测试了...可能会很久（深圳.jpg）

**Comment by VA1ue-0268** [comment]
(゜o゜;  问题不大问题不大，等dalao有条件再慢慢看看，现在暂时用笨方法（连续发包）解决了(*﹏*;)，深圳要注意安全呀

**Comment by Sucareto** [comment]
或许是需要连续发包...我试了一下，在`ConditioningMode = false;`之后无论什么情况都给游戏发包，情况是正常的。
我晚点用mpr121再详细测一下。
顺带一提，只要Mai2Touch正常工作，`DummyTouchPanel=1`也是没问题的。

**Comment by VA1ue-0268** [comment]
是这样子咩qwq，但是我`DummyTouchPanel=1`的话不就是上面的情况哎...无法长按，晚点大佬测出更好的方法还请多多指点。

**Comment by fangxx3863** [comment]
借楼请教一下大佬,外键能走COM输入吗？

**Comment by Sucareto** [comment]
> 借楼请教一下大佬,外键能走COM输入吗？

不可以，外键是走amdaemon的，要实现只能修改hook。

**Comment by fangxx3863** [comment]
> > 借楼请教一下大佬,外键能走COM输入吗？
> 
> 不可以，外键是走amdaemon的，要实现只能修改hook。

感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了

**Comment by VA1ue-0268** [comment]
> > > 借楼请教一下大佬,外键能走COM输入吗？
> > 
> > 
> > 不可以，外键是走amdaemon的，要实现只能修改hook。
> 
> 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了

试试单片机模拟键盘？延迟应该可以接受的

**Comment by Sucareto** [comment]
> 是这样子咩qwq，但是我`DummyTouchPanel=1`的话不就是上面的情况哎...无法长按，晚点大佬测出更好的方法还请多多指点。

我用chuni台的mpr121测试了触摸，是工作正常的。
试下我的最新commit？

**Comment by fangxx3863** [comment]
> > > > 借楼请教一下大佬,外键能走COM输入吗？
> > > 
> > > 
> > > 不可以，外键是走amdaemon的，要实现只能修改hook。
> > 
> > 
> > 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了
> 
> 试试单片机模拟键盘？延迟应该可以接受的

我之前就是328P做的VUSB,延迟不行
后来换成串口结合上位机配合大漠插件延迟就下来了,但是还是感觉有那么点反应迟钝（也有可能是我打歌技术太菜了

**Comment by Sucareto** [comment]
> > > > > 借楼请教一下大佬,外键能走COM输入吗？
> > > > 
> > > > 
> > > > 不可以，外键是走amdaemon的，要实现只能修改hook。
> > > 
> > > 
> > > 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了
> > 
> > 
> > 试试单片机模拟键盘？延迟应该可以接受的
> 
> 我之前就是328P做的VUSB,延迟不行 后来换成串口结合上位机配合大漠插件延迟就下来了,但是还是感觉有那么点反应迟钝（也有可能是我打歌技术太菜了

你可以试下32u4或者samd21这种支持HID的，能同时支持键盘和串口，我测试过没感觉到有延迟。

**Comment by fangxx3863** [comment]
> > > > > > 借楼请教一下大佬,外键能走COM输入吗？
> > > > > 
> > > > > 
> > > > > 不可以，外键是走amdaemon的，要实现只能修改hook。
> > > > 
> > > > 
> > > > 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了
> > > 
> > > 
> > > 试试单片机模拟键盘？延迟应该可以接受的
> > 
> > 
> > 我之前就是328P做的VUSB,延迟不行 后来换成串口结合上位机配合大漠插件延迟就下来了,但是还是感觉有那么点反应迟钝（也有可能是我打歌技术太菜了
> 
> 你可以试下32u4或者samd21这种支持HID的，能同时支持键盘和串口，我测试过没感觉到有延迟。

（当时觉得太贵了就没搞
PCB都打了,都封好了就懒得搞了
![IMG_20220319_182756](https://user-images.githubusercontent.com/48589001/159117421-4b9b4244-0931-47d0-8e99-40821044a2e5.jpg)
![IMG_20220319_182809](https://user-images.githubusercontent.com/48589001/159117426-3d4e7533-c4f0-43a8-8f47-4be461829b89.jpg)

**Comment by Sucareto** [comment]
> > > > > > > 借楼请教一下大佬,外键能走COM输入吗？
> > > > > > 
> > > > > > 
> > > > > > 不可以，外键是走amdaemon的，要实现只能修改hook。
> > > > > 
> > > > > 
> > > > > 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了
> > > > 
> > > > 
> > > > 试试单片机模拟键盘？延迟应该可以接受的
> > > 
> > > 
> > > 我之前就是328P做的VUSB,延迟不行 后来换成串口结合上位机配合大漠插件延迟就下来了,但是还是感觉有那么点反应迟钝（也有可能是我打歌技术太菜了
> > 
> > 
> > 你可以试下32u4或者samd21这种支持HID的，能同时支持键盘和串口，我测试过没感觉到有延迟。
> 
> （当时觉得太贵了就没搞 PCB都打了,都封好了就懒得搞了 ![IMG_20220319_182756](https://user-images.githubusercontent.com/48589001/159117421-4b9b4244-0931-47d0-8e99-40821044a2e5.jpg) ![IMG_20220319_182809](https://user-images.githubusercontent.com/48589001/159117426-3d4e7533-c4f0-43a8-8f47-4be461829b89.jpg)

哇这个按键是怎么做的呀？

**Comment by CoolBreezeArcanine** [comment]
这个按键方案看上去有点不错诶，就是手真的不会被搓掉皮吗hhh
插个眼

**Comment by fangxx3863** [comment]
> 这个按键方案看上去有点不错诶，就是手真的不会被搓掉皮吗hhh 插个眼

本来想入官方按键的,但是价格真心劝退 
淘宝翻了好久才发现这个脚踏开关非常合适,这8个一共才30多 
另外,硌手问题带上手套没感觉,实在不行拿砂纸打一下也不是不行

**Comment by fangxx3863** [comment]
我方案大概就是直接买触摸屏 
我是19寸的20点电容屏 
然后亚克力切个板扣上去 
按键是脚踏开关,拆出来自己改光电门 
亚克力先拿了Fusion 360建了模然后导出CAD去淘宝找人切
![IMG_20220226_152538](https://user-images.githubusercontent.com/48589001/159133541-d525a0c8-55e7-4412-a838-d25b992deb41.jpg)
![IMG_20220226_152525](https://user-images.githubusercontent.com/48589001/159133549-3c6c1853-02d2-433e-b55b-a24a0f14f90b.jpg)
![IMG20220220163303](https://user-images.githubusercontent.com/48589001/159133551-93fd8c53-cb58-44fa-b7e1-0b1f9dc14b60.jpg)

**Comment by VA1ue-0268** [comment]
> > 是这样子咩qwq，但是我`DummyTouchPanel=1`的话不就是上面的情况哎...无法长按，晚点大佬测出更好的方法还请多多指点。
> 
> 我用chuni台的mpr121测试了触摸，是工作正常的。 试下我的最新commit？

好！谢谢大佬！

**Comment by VA1ue-0268** [comment]
> 我方案大概就是直接买触摸屏 我是19寸的20点电容屏 然后亚克力切个板扣上去 按键是脚踏开关,拆出来自己改光电门 亚克力先拿了Fusion 360建了模然后导出CAD去淘宝找人切 ![IMG_20220226_152538](https://user-images.githubusercontent.com/48589001/159133541-d525a0c8-55e7-4412-a838-d25b992deb41.jpg) ![IMG_20220226_152525](https://user-images.githubusercontent.com/48589001/159133549-3c6c1853-02d2-433e-b55b-a24a0f14f90b.jpg) ![IMG20220220163303](https://user-images.githubusercontent.com/48589001/159133551-93fd8c53-cb58-44fa-b7e1-0b1f9dc14b60.jpg)

喔不错的方案哎

**Comment by CY202032** [comment]
你好，我是用的的工程，Mpr121后一切是正常的，不知道为什么只有E7,E8是无法测试的，没有任何反应，我换了121的地址也是没有作用的，请问只有我是这种情况吗？

**Comment by Sucareto** [comment]
> 你好，我是用的的工程，Mpr121后一切是正常的，不知道为什么只有E7,E8是无法测试的，没有任何反应，我换了121的地址也是没有作用的，请问只有我是这种情况吗？

先确认mpr121是否工作正常，如果没问题，可以参考以下代码手动设置：
```
#define sA1(x) bitWrite(TouchData, 0, x)//设置 sensor
#define sB1(x) bitWrite(TouchData, 8, x)
#define sC1(x) bitWrite(TouchData, 16, x)
#define sD1(x) bitWrite(TouchData, 18, x)
#define sE1(x) bitWrite(TouchData, 26, x)
#define sE7(x) bitWrite(TouchData, 32, x)

sE7(1);//按下
```

**Comment by Sucareto** [comment]
> 你好，我是用的的工程，Mpr121后一切是正常的，不知道为什么只有E7,E8是无法测试的，没有任何反应，我换了121的地址也是没有作用的，请问只有我是这种情况吗？

先确认mpr121是否工作正常，如果没问题，可以参考以下代码手动设置：
```
#define sA1(x) bitWrite(TouchData, 0, x)//设置 sensor
#define sB1(x) bitWrite(TouchData, 8, x)
#define sC1(x) bitWrite(TouchData, 16, x)
#define sD1(x) bitWrite(TouchData, 18, x)
#define sE1(x) bitWrite(TouchData, 26, x)
#define sE7(x) bitWrite(TouchData, 32, x)

sE7(1);//按下
```

**Comment by CY202032** [comment]
还是不行，不知道为什么地址到03就在按下一个不发送07跟0F，找不出问题，哎，难搞啊，单独测试5A 5B 5C，三块MPR121均为好的，不知道是不是主控的问题，atmega32u4, mpr121 -Breakout-v12接近电容式触摸传感器
![无标题](https://user-images.githubusercontent.com/102383219/160249294-ff2e8c0a-4094-4bc8-9a8b-d7b1d8380c40.jpg)

**Comment by CY202032** [comment]
> > > > > > 借楼请教一下大佬,外键能走COM输入吗？
> > > > > 
> > > > > 
> > > > > 不可以，外键是走amdaemon的，要实现只能修改hook。
> > > > 
> > > > 
> > > > 感谢回复,我做外键用键盘输入总感觉有延迟,看来这样很难搞了
> > > 
> > > 
> > > 试试单片机模拟键盘？延迟应该可以接受的
> > 
> > 
> > 我之前就是328P做的VUSB,延迟不行 后来换成串口结合上位机配合大漠插件延迟就下来了,但是还是感觉有那么点反应迟钝（也有可能是我打歌技术太菜了
> 
> 你可以试下32u4或者samd21这种支持HID的，能同时支持键盘和串口，我测试过没感觉到有延迟。

我没有用32u4支持外键，外键完全是PCB，键盘比较麻烦，改成手柄输入了，非常方便，也不会影响系统该死的输入法

**Comment by CY202032** [comment]
问题得到解决，由于寻址问题，多了连个触摸板，会被逆向寻掉。
  SerialDevice.write('(');
  SerialDevice.write((TouchData >> 0)& B11111);
  SerialDevice.write((TouchData >> 5)& B11111);
  SerialDevice.write((TouchData >> 10)& B11111);
  SerialDevice.write((TouchData >> 15)& B11111);
  SerialDevice.write((TouchData >> 20)& B11111);
  SerialDevice.write((TouchData >> 25)& B11111);
  SerialDevice.write((TouchData >> 28)& B11111);
  SerialDevice.write(')');
这样就全了，E7 E8都正常了。
目前还有一个问题比较困扰，那就是鬼畜问题，程序会不停发包，导致鬼畜触摸，不知道是什么原因- -~

**Comment by CY202032** [comment]
> 嗯嗯，麻烦大佬再帮忙看看qwq 下面是串口图片和效果视频
> 
> ![image](https://user-images.githubusercontent.com/17075414/158346844-ebc04c79-8c5c-4825-8700-b7de2369f5fd.png)
> 
>  VID_20220315_171841_new_file.1._x264.mp4

请问兄弟屏幕在哪里定的？有链接吗？

**Comment by VA1ue-0268** [comment]
> > 嗯嗯，麻烦大佬再帮忙看看qwq 下面是串口图片和效果视频
> > ![image](https://user-images.githubusercontent.com/17075414/158346844-ebc04c79-8c5c-4825-8700-b7de2369f5fd.png)
> > VID_20220315_171841_new_file.1._x264.mp4
> 
> 请问兄弟屏幕在哪里定的？有链接吗？

抱歉最近忙开学的没看git，触控是ito膜自己割的，淘宝很多卖

**Comment by CY202032** [comment]
> > > 嗯嗯，麻烦大佬再帮忙看看qwq 下面是串口图片和效果视频
> > > ![image](https://user-images.githubusercontent.com/17075414/158346844-ebc04c79-8c5c-4825-8700-b7de2369f5fd.png)
> > > VID_20220315_171841_new_file.1._x264.mp4
> > 
> > 
> > 请问兄弟屏幕在哪里定的？有链接吗？
> 
> 抱歉最近忙开学的没看git，触控是ito膜自己割的，淘宝很多卖

那您是用的mpr121么？我用了mpr121会鬼畜，还有一个问题，就是绝缘皮触摸都会有反应- -~

**Comment by VA1ue-0268** [comment]
> > > > 嗯嗯，麻烦大佬再帮忙看看qwq 下面是串口图片和效果视频
> > > > ![image](https://user-images.githubusercontent.com/17075414/158346844-ebc04c79-8c5c-4825-8700-b7de2369f5fd.png)
> > > > VID_20220315_171841_new_file.1._x264.mp4
> > > 
> > > 
> > > 请问兄弟屏幕在哪里定的？有链接吗？
> > 
> > 
> > 抱歉最近忙开学的没看git，触控是ito膜自己割的，淘宝很多卖
> 
> 那您是用的mpr121么？我用了mpr121会鬼畜，还有一个问题，就是绝缘皮触摸都会有反应- -~

鬼畜的话要看datasheet慢慢调参数，我也没有完全解决qwq，绝缘皮触摸有反应应该是正常现象，我的也会，可能要做屏蔽

**Comment by Sucareto** [comment]
> 问题得到解决，由于寻址问题，多了连个触摸板，会被逆向寻掉。 SerialDevice.write('('); SerialDevice.write((TouchData >> 0)& B11111); SerialDevice.write((TouchData >> 5)& B11111); SerialDevice.write((TouchData >> 10)& B11111); SerialDevice.write((TouchData >> 15)& B11111); SerialDevice.write((TouchData >> 20)& B11111); SerialDevice.write((TouchData >> 25)& B11111); SerialDevice.write((TouchData >> 28)& B11111); SerialDevice.write(')'); 这样就全了，E7 E8都正常了。 目前还有一个问题比较困扰，那就是鬼畜问题，程序会不停发包，导致鬼畜触摸，不知道是什么原因- -~

问题解决了，是因为`bitWrite`不支持`uint64_t`，后面那部分的数据没有设置成功，已经在示例里面添加了`bitWrite64`的宏；
在最新的提交里面改用了另外一种设置值的方法，可以不需要`bitWrite`了；
鬼畜的原因，是mpr121的调教问题，可以参考这篇[MPR121配置寄存器调参指南](https://bemani.cc/d/77-mpr121)
也可以使用代码里的[高级设置方法](https://github.com/Sucareto/Mai2Touch/blob/1bb2f1d09d832d71237b1b676a847aa3a165ade3/Mai2Touch.ino#L138)。

**Comment by CoolBreezeArcanine** [comment]
是个好方案，把脚踏开关打磨一下就不错了。里面是你自己把它原来的微动抠掉换的光眼吗？
以及触屏是个什么方案




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月20日(星期天) 凌晨2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sucareto/Mai2Touch] 请教一下如何实现长按？ (Issue #1)





 
我方案大概就是直接买触摸屏
 我是19寸的20点电容屏
 然后亚克力切个板扣上去
 按键是脚踏开关,拆出来自己改光电门
 亚克力先拿了Fusion 360建了模然后导出CAD去淘宝找人切
 
 
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
