### ISSUE TITLE
LED数据不同处

### ISSUE THREAD

**Issue by CY202032** [Sucareto/Mai2Touch#2]
>>> e0 11 01 01 f0 03
<<< e0 01 11 0d 01 f0 01 31 35 30 37 30 2d 30 34 ff 90 2e该数据应该是15070-02-91的数据该的。
        E0 01 11 0F 01 F0 01 31 35 30 37 30 2D 30 34 FF 90 00 30 60此数据为15070-04的数据
>>> e0 11 01 01 f3 06
<<< e0 01 11 06 01 f3 01 01 00 00 0e
        E0 01 11 06 01 F3 01 01 01 01 10

>>> e0 11 01 01 f1 04
<<< e0 01 11 07 01 f1 01 00 00 00 00 0c
        E0 01 11 07 01 F1 01 00 01 00 00 0D

目前发现不同处3处，其他未知，可以联系我获取更多的数据。。。id就是wx

**Comment by Sucareto** [comment]
目前尚未捕获到官方灯光控制器的串口数据，[Mai2LED](https://github.com/Sucareto/Mai2Touch/tree/main/Mai2LED) 是通过猜测构建的。
如果你愿意提供数据作为参考那就最好啦~
但很遗憾我并没有在使用微信，如果方便的话，Discord 或者 QQ 的话怎么样？

**Comment by CY202032** [comment]
QQ也行哇~183234999
